### PR TITLE
Add Dockerfile to get the tokens

### PR DESCRIPTION
**Pull request by DavidDeSloovere**
#33 
Most of this is generated. Readme got automatically formatted after I changed the content.

I was able to build and the container successfully in VS Code.

The next step would be to build the container in a Github action a publish it to either your repo's Artifacts or official Docker hub. I have done that recently in [my own project](https://github.com/DavidDeSloovere/giphy-cli).

I wonder if this should go into a separate repo.

### CODE REVIEW

**Comment by Chouffy** [comment]
Hey @DavidDeSloovere , thanks a lot for your PR! It sounds really great and I appreciate the time and effort you put into this. 
However I'm out of any computer for the next few months and I would like to test it before merging. 
Do you mind to wait a bit?

**Comment by Chouffy** [comment]
@maartenhendrix : do you think you could give me a help here, if you want and can?

**Comment by maartenhendrix** [comment]
I'm not sure if I can. Also not near a computer for some time 😬

**Comment by DavidDeSloovere** [comment]
Update for latest version.

**Comment by Chouffy** [comment]
Hey @DavidDeSloovere  thanks for updating this!
Few questions as I'm not experienced in Docker:
- Is it expected that there's `docker build docker build` on [this line](https://github.com/Chouffy/home_assistant_tgtg/pull/35/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R44)
- Do we have to use the `homeassistant_tgtg_tokens` tag? is it a docker tar or a git branch? #noobhere

**Comment by DavidDeSloovere** [comment]
Only 1 `docker build` is required. Good catch!

In `homeassistant_tgtg_tokens:latest`, `homeassistant_tgtg_tokens` is the name of the image and `latest` is the tag. Better to name it explicitly, I vaguely recall that otherwise it uses the github repo name, which could change. If you want to use `home_assistant_tgtg_tokens`, that's fine also. It's just the local image. As there is no push to the docker registry (for now). If you push from github to docke registry, then people would not need to build the image locally.

Had merge conflicts on readme, I can work with git (somewhat), but not experienced with github flow, forks etc... so hope I didn't make it worse.

**Comment by tjorim** [comment]
LGTM, it would be nice to add a pre-built docker image.
It should be possible to build and host it here with some GitHub Actions.
For now, this is already an improvement IMO.

**Comment by DavidDeSloovere** [comment]
On another project I have a GH action that builds and uploads the image into the artifacts of the repo.
https://github.com/DavidDeSloovere/giphy-cli/blob/main/.github/workflows/publish.yml

Might be better in a separate PR.

**Comment by tjorim** [comment]
> On another project I have a GH action that builds and uploads the image into the artifacts of the repo.
> https://github.com/DavidDeSloovere/giphy-cli/blob/main/.github/workflows/publish.yml
> 
> Might be better in a separate PR.

Agreed, merged first version.

**Comment by DasPflanze** [comment]
Hey everyone,
the provided solution to get the tokens with docker seems to be a bit bloated for only running one script. It took several minutes on my server to run it. On another issue I posted my way a ran the skript:
https://github.com/Chouffy/home_assistant_tgtg/issues/72#issuecomment-1494629320
If you want some help I could try to write everything into a dockerfile, so you only have to build and run it.

**Pull request merged**
