### PR TITLE
Adding support for more than 25 favourites

### PR DESCRIPTION
**Pull request by flipperdolphin**
Currently, the integration doesn't allow for more than 20/25 favourite items as documented here #29 

This PR adds support for customising the number of items that are retrieved on initial load, allowing the integration to handle more favourites.

Not sure on naming the config variable 'page_size' - Welcome to change this but not feeling super creative 

This has been tested with 30 favourites and worked 👍

### CODE REVIEW

**Comment by Chouffy** [comment]
Hey @flipperdolphin thanks a lot for your PR!
Maybe a small question: is it necessary to define a default value in this code?
There's already one defined in the `tgtg` module. 

However I don't remember how Python will behave if we have no value defined like `vol.Optional(CONF_PAGE_SIZE, default=""): cv.string,` ... Will it indeed fallback to the value defined in [https://github.com/ahivert/tgtg-python/blob/master/tgtg/__init__.py#L213](https://github.com/ahivert/tgtg-python/blob/master/tgtg/__init__.py#L213)?
I don't have a PC to check that now 🤔

**Comment by flipperdolphin** [comment]
Just taking a look at this. If we just removed the 20 from `        vol.Optional(CONF_PAGE_SIZE, default="20"): cv.string,
` it would fail as page_size would equal 0 (tested this) - I'd assume because our default is empty but we're still trying to pass it through. 

We could check if the value is empty and if so, don't pass in page_size to the tgtg-python module. Might be better to fall back onto the module's value rather than defining our own here.

**Comment by tjorim** [comment]
@flipperdolphin are you still planning on updating this PR with the suggestion provided?

**Comment by flipperdolphin** [comment]
> @flipperdolphin are you still planning on updating this PR with the suggestion provided?

Completely forgot about this as I've been using the modified version locally on my install without issue. I'll try and update with the changes soon unless anyone else does :)

**Comment by tjorim** [comment]
Closing in favor of #70.

**Pull request closed without merging**
